/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 23/08/2020 23:36:46          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'localhost:C:\Users\vinic\Documents\Embarcadero\Studio\Projects\VNTEstoque\Banco\BANCO.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_CIDADE;
SET GENERATOR GEN_CIDADE TO 0;

CREATE GENERATOR GEN_ESTADO;
SET GENERATOR GEN_ESTADO TO 0;

CREATE GENERATOR GEN_PESSOA;
SET GENERATOR GEN_PESSOA TO 0;

CREATE GENERATOR GEN_PRODUTO;
SET GENERATOR GEN_PRODUTO TO 0;

CREATE GENERATOR GEN_USUARIO;
SET GENERATOR GEN_USUARIO TO 0;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CIDADE (
    ID          INTEGER NOT NULL,
    NOME        VARCHAR(40) NOT NULL,
    ID_ESTADO   INTEGER,
    CODIGOIBGE  INTEGER
);

CREATE TABLE ESTADO (
    ID        INTEGER NOT NULL,
    NOME      VARCHAR(30) NOT NULL,
    UF        CHAR(2),
    CODIGOUF  INTEGER
);

CREATE TABLE PESSOA (
    ID            INTEGER NOT NULL,
    DATACADASTRO  DATE,
    DATAEXCLUSAO  DATE,
    USUARIO       INTEGER,
    NOME          VARCHAR(255),
    NOMEFANTASIA  VARCHAR(255),
    CPFCNPJ       VARCHAR(18),
    IERG          VARCHAR(12),
    SEXO          CHAR(1),
    RUA           VARCHAR(255),
    NUMERO        VARCHAR(4),
    BAIRRO        VARCHAR(150),
    CEP           VARCHAR(10),
    ID_CIDADE     INTEGER,
    DATANASC      DATE,
    COMPLEMENTO   VARCHAR(100),
    OBSERVACOES   VARCHAR(300),
    TIPOUSUAIRO   CHAR(1),
    TELEFONE1     VARCHAR(14),
    TELEFONE2     VARCHAR(14),
    EMAIL1        VARCHAR(100),
    IMG           BLOB SUB_TYPE 0 SEGMENT SIZE 80
);

CREATE TABLE PRODUTO (
    ID                INTEGER NOT NULL,
    DATACADASTRO      DATE,
    DATAEXCLUSAO      DATE,
    ID_USUARIO        INTEGER,
    DESCRICAO         VARCHAR(50),
    CODIGOBARRA       VARCHAR(25),
    ESTOQUE           DECIMAL(15,2),
    ESTOQUEMINIMO     DECIMAL(15,2),
    VALORCOMPRA       DECIMAL(15,2),
    VALORVENDA        DECIMAL(15,2),
    PORCENTAGEMLUCRO  DECIMAL(15,2),
    UNIDADEMEDIA      VARCHAR(2),
    OBSERVACOES       VARCHAR(255),
    CONTROLEESTOQUE   CHAR(1)
);

CREATE TABLE USUARIO (
    ID            INTEGER NOT NULL,
    DATACADASTRO  DATE,
    DATAEXCLUSAO  DATE,
    NOME          VARCHAR(100) NOT NULL,
    SENHA         VARCHAR(100)
);



/******************************************************************************/
/***                           Unique Constraints                           ***/
/******************************************************************************/

ALTER TABLE USUARIO ADD UNIQUE (NOME);


/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CIDADE ADD PRIMARY KEY (ID);
ALTER TABLE ESTADO ADD PRIMARY KEY (ID);
ALTER TABLE PESSOA ADD PRIMARY KEY (ID);
ALTER TABLE PRODUTO ADD PRIMARY KEY (ID);
ALTER TABLE USUARIO ADD PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE CIDADE ADD FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID);
ALTER TABLE PESSOA ADD FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID);
