Insert into Estado (CodigoUf, Nome, Uf) values (12, 'Acre', 'AC');
Insert into Estado (CodigoUf, Nome, Uf) values (27, 'Alagoas', 'AL');
Insert into Estado (CodigoUf, Nome, Uf) values (16, 'Amapá', 'AP');
Insert into Estado (CodigoUf, Nome, Uf) values (13, 'Amazonas', 'AM');
Insert into Estado (CodigoUf, Nome, Uf) values (29, 'Bahia', 'BA');
Insert into Estado (CodigoUf, Nome, Uf) values (23, 'Ceará', 'CE');
Insert into Estado (CodigoUf, Nome, Uf) values (53, 'Distrito Federal', 'DF');
Insert into Estado (CodigoUf, Nome, Uf) values (32, 'Espírito Santo', 'ES');
Insert into Estado (CodigoUf, Nome, Uf) values (52, 'Goiás', 'GO');
Insert into Estado (CodigoUf, Nome, Uf) values (21, 'Maranhão', 'MA');
Insert into Estado (CodigoUf, Nome, Uf) values (51, 'Mato Grosso', 'MT');
Insert into Estado (CodigoUf, Nome, Uf) values (50, 'Mato Grosso do Sul', 'MS');
Insert into Estado (CodigoUf, Nome, Uf) values (31, 'Minas Gerais', 'MG');
Insert into Estado (CodigoUf, Nome, Uf) values (15, 'Pará', 'PA');
Insert into Estado (CodigoUf, Nome, Uf) values (25, 'Paraíba', 'PB');
Insert into Estado (CodigoUf, Nome, Uf) values (41, 'Paraná', 'PR');
Insert into Estado (CodigoUf, Nome, Uf) values (26, 'Pernambuco', 'PE');
Insert into Estado (CodigoUf, Nome, Uf) values (22, 'Piauí', 'PI');
Insert into Estado (CodigoUf, Nome, Uf) values (33, 'Rio de Janeiro', 'RJ');
Insert into Estado (CodigoUf, Nome, Uf) values (24, 'Rio Grande do Norte', 'RN');
Insert into Estado (CodigoUf, Nome, Uf) values (43, 'Rio Grande do Sul', 'RS');
Insert into Estado (CodigoUf, Nome, Uf) values (11, 'Rondônia', 'RO');
Insert into Estado (CodigoUf, Nome, Uf) values (14, 'Roraima', 'RR');
Insert into Estado (CodigoUf, Nome, Uf) values (42, 'Santa Catarina', 'SC');
Insert into Estado (CodigoUf, Nome, Uf) values (35, 'São Paulo', 'SP');
Insert into Estado (CodigoUf, Nome, Uf) values (28, 'Sergipe', 'SE');
Insert into Estado (CodigoUf, Nome, Uf) values (17, 'Tocantins', 'TO');